#!/usr/bin/env python3
"""Build the self-contained Verilog file used by custom_gds.

The Tiny Tapeout custom_gds action copies one Verilog file into the submission
artifact.  This project keeps the real RTL split across src/ with `include
directives, so this script expands the local project sources into one file
while preserving the normal source files for simulation, FPGA, and local TT
builds.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

INCLUDE_RE = re.compile(r'^\s*`include\s+"[^"]+"\s*$')
MODULE_RE = re.compile(r'^\s*module\s+([A-Za-z_][\w$]*)\b', re.MULTILINE)

SOURCE_ORDER = [
    "project.v",
]


def strip_local_includes(text: str) -> str:
    lines: list[str] = []
    for line in text.splitlines():
        if INCLUDE_RE.match(line):
            lines.append("/* local include expanded by tools/build_custom_gds_verilog.py */")
        else:
            lines.append(line)
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--src", default="src", help="Source directory")
    parser.add_argument("--out", required=True, help="Output Verilog file")
    args = parser.parse_args()

    src_dir = Path(args.src)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    parts: list[str] = []
    parts.append("/*\n")
    parts.append(" * Generated by tools/build_custom_gds_verilog.py.\n")
    parts.append(" * Do not edit this file by hand.  Edit the source files under src/.\n")
    parts.append(" */\n\n")

    print("Expanding Verilog sources for custom_gds:")
    for rel in SOURCE_ORDER:
        path = src_dir / rel
        if not path.is_file():
            raise FileNotFoundError(path)
        text = path.read_text()
        line_count = text.count("\n") + 1
        print(f"  src/{rel}: {len(text)} bytes, {line_count} lines")
        parts.append("\n/* ---- begin expanded source: src/%s ---- */\n" % rel)
        parts.append(strip_local_includes(text))
        parts.append("/* ---- end expanded source: src/%s ---- */\n" % rel)

    out_path.write_text("".join(parts))

    generated = out_path.read_text()
    remaining_includes = [line for line in generated.splitlines() if INCLUDE_RE.match(line)]
    if remaining_includes:
        raise RuntimeError("Generated file still contains active `include directives")

    modules = MODULE_RE.findall(generated)
    print()
    print(f"Wrote {out_path}: {len(generated)} bytes, {generated.count(chr(10)) + 1} lines")
    print(f"Found {len(modules)} module declarations:")
    for module in modules:
        print(f"  {module}")
    print("No active `include directives remain.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
